# Generated by Django 3.1.7 on 2021-05-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songdetail',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9),
        ),
    ]
